# Generated by Django 5.0.4 on 2024-08-04 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_contact_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(default='', max_length=13),
        ),
    ]
